name: client-ci
on:
  push: { branches: [ ai-main ] }
  pull_request: { branches: [ ai-main ] }
jobs:
  build-client:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build Avalonia
      run: dotnet build client/BelieveOrNot.Client.Avalonia -c Release --no-restore
